### PR TITLE
GUI update

### PR DESCRIPTION
**Pull request by cnguyenm**
1. MainMenu
  - music, effects, nice girl
  - basic navigation (not do much for now)
  - Scene: MainMenuBeauty
2. In-game menu
  * Settings
  * Inventory
       - show list of weapons
       - description
3. new HUD
4. Others
  - GUI code is more organized
  - new sprites 
5. Improvement
  - Save game and transition scene is still a challenge
  - Inventory system will be more systematic (add, drop, equip functionality)
6. Most things are just the look for now, not many functionalities.

### CODE REVIEW

**Comment by Lonswaya** [comment]
Call me the anti-weeb, but can I change the main menu? 

I'm thinking I can set up a camera to show some enemies roaming a dungeon. Either that or the island in the beginning with the player in front.

**Comment by VinsonL19** [comment]
I do hope that this is just a joke and not something we are doing for real.
As hilarious as this is, the anime background is definitely not something we should have in our final product for numerous reasons: possible copyright infringement, extreme contrasting styles, unfit in the game, and poor taste (because I hate anime, anime sucks, triggers me to no end).

If this is just as a place holder, that is perfectly fine! All for shits and giggles. But the main menu for the final product should be related to the game itself, like maybe what Andrew suggests, or just camera looking at front side of the main character in full body armor.

**Comment by Lonswaya** [comment]
^ he hates anime so don't take it personally

**Comment by Lonswaya** [comment]
Working on a replacement at the moment

**Comment by Lonswaya** [comment]
Bugs found: 
-picking up two weapons and swapping them out leaves duplicate entries in the list
-all values (health, magic, light) should probably be rounded off (92 instead of 92.1572357421)

Fix those two and this should be good to go

Eventually, we should probably show weapon condition in the main GUI. That way players know how much damage they are doing to the enemy, and their weapon's condition.

**Comment by cnguyenm** [comment]
yeah, I will fix: 
 * main menu
 * duplicate entries

**Comment by Lonswaya** [comment]
Looks like duplicate items still show up in magic, and probably will in armor as well.

Also, I think condition should not be rounded, I meant the health, light, and magic in-game. Round each to two decimal places, like 100.00 
The weapon condition can probably stay the same.

Also, I fixed an issue with light not updating in the GUI when in the dungeon

**Review by Lonswaya — APPROVED** [review]
Good enough for now. Hopefully we can get to armor and weapon/stat upgrades next.

**Comment by cnguyenm** [comment]
Yeah. ^^

**Pull request merged**
